//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by A Note.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_TINYNOTYPE                  129
#define IDD_NOTE                        130
#define IDR_TRAYMAIN                    131
#define IDI_TRAYMAIN                    132
#define IDI_ALARM                       133
#define IDD_OPTIONS                     133
#define IDI_ALARM1                      134
#define IDD_SETTITLE                    134
#define IDD_SETALARM                    135
#define IDI_DOWNLOADNOTE                135
#define IDD_SNOOZE                      136
#define IDI_DOWNLOADNOTE1               136
#define IDR_POPUPMENU                   137
#define IDI_DOWNLOADNOTE2               137
#define IDB_NOTEALARM                   138
#define IDI_DOWNLOADNOTE3               138
#define IDB_NOTEMINIMIZE                139
#define IDI_DOWNLOADNOTE4               139
#define IDB_NOTECLOSE                   140
#define IDI_DOWNLOADNOTE5               140
#define IDR_MENUBAR                     141
#define IDI_DOWNLOADNOTE6               141
#define IDI_DOWNLOADNOTE7               142
#define IDI_UPLOADNOTE                  143
#define IDB_LOGOTYPE                    144
#define IDI_UPLOADNOTE1                 144
#define IDI_UPLOADNOTE2                 145
#define IDI_UPLOADNOTE3                 146
#define IDD_DLGHELPTRAY                 147
#define IDI_UPLOADNOTE4                 147
#define IDB_DLGTRAY                     148
#define IDI_UPLOADNOTE5                 148
#define IDD_DLGTRIALVERSION             149
#define IDB_NOTEMINIMIZE1               149
#define IDI_UPLOADNOTE6                 149
#define IDB_NOTECLOSE1                  150
#define IDI_UPLOADNOTE7                 150
#define IDB_NOTEMINIMIZE2               151
#define IDB_NOTEALARM1                  152
#define IDD_OPTIONSGENERAL              152
#define IDD_OPTIONSLOOKS                153
#define IDB_NOTEMINIMIZE3               153
#define IDD_ENTERKEY                    154
#define IDD_DLGGUIDE                    154
#define IDB_NOTEBULLET                  154
#define IDD_OPTIONSALARM                155
#define IDB_NOTEBULLET1                 155
#define IDR_ALARMSOUND                  156
#define IDD_OPTIONSDATABASE             156
#define IDB_SLIDERIGHT                  156
#define IDB_SLIDERIGHT1                 157
#define IDB_SLIDELEFT                   158
#define IDB_SLIDELEFT1                  159
#define IDD_USERINFORMATION             162
#define IDD_USEUSERINFORMATION          163
#define IDD_OPTIONSFONT                 164
#define IDD_OPTIONSNEWNOTE              165
#define IDD_OPTIONSTRANSPARANCY         166
#define IDD_OPTIONSHOTKEY               167
#define IDD_OPTIONSSERVER               168
#define IDD_SELECTRECIPIENT             169
#define IDD_RECYCLEBIN                  170
#define IDD_RECYCLEBINHELP              171
#define IDD_OPTIONSRECYCLEBIN           172
#define IDD_DELETEINFORMATION           173
#define IDD_OPTIONSTOOLBAR              174
#define IDB_TOOLBAR                     174
#define IDB_BOLD                        175
#define IDD_OPTIONSBEHAVIOUR            175
#define IDB_BOLD1                       176
#define IDD_LANGUAGE                    176
#define IDB_UNDERLINE                   177
#define IDD_OPTIONSLANGUAGE             177
#define IDB_UNDERLINE1                  178
#define IDB_ITALIC                      179
#define IDD_CREATENEWLANGUAGE           179
#define IDB_ITALIC1                     180
#define IDI_TRAYMAIN1                   180
#define IDD_OPTIONSCHARSET              180
#define IDB_STRIKEOUT                   181
#define IDB_STRIKEOUT1                  182
#define IDC_NOTECOLOR                   1000
#define IDC_START                       1001
#define IDC_TRANSPARANCY                1002
#define IDC_TITLE                       1003
#define IDC_TRANSPARANCYMINIMIZE        1003
#define IDC_USEALARM                    1004
#define IDC_TIME                        1005
#define IDC_DATE                        1006
#define IDC_SHOWAGAIN                   1007
#define IDC_PERIODICTIME                1007
#define IDC_PROGRESS1                   1008
#define IDC_USEPERIDICALARM             1008
#define IDC_HYPERLINK                   1009
#define IDC_EVERYDAY                    1009
#define IDC_DAYSLEFT                    1010
#define IDC_EVERYWEEK                   1010
#define IDC_EVERYMONTH                  1011
#define IDC_RADIO1                      1011
#define IDC_CLICKONCE                   1012
#define IDC_RADIO2                      1013
#define IDC_RADIO3                      1014
#define IDC_EVERYDAYDAY                 1015
#define IDC_EVERYWEEKDAY                1016
#define IDC_PAGE_TREE                   1016
#define IDC_EVERYMONTHDAY               1017
#define IDC_CAPTION_BAR                 1017
#define IDC_DLG_FRAME                   1018
#define IDC_FASTCREATE                  1020
#define IDC_WARNONDELETE                1021
#define IDC_DEFAULTTITLE                1022
#define IDC_RNDCOLOR                    1023
#define IDC_PASSWORD                    1023
#define IDC_VERSIONCHECK                1023
#define IDC_HIDEONMINIMIZE              1025
#define IDC_THINBORDER                  1026
#define IDC_STATIC1                     1027
#define IDC_DOCKABLE                    1027
#define IDC_STATIC2                     1028
#define IDC_DOUBLECLICKTITLEBAR         1028
#define IDC_ENTERKEY                    1029
#define IDC_MINIMIZEMOVECURSOR          1029
#define IDC_NAME                        1031
#define IDC_KEY                         1032
#define IDC_BLINK                       1032
#define IDC_PLAYSOUND                   1033
#define IDC_USERNAME                    1033
#define IDC_UPLOADDOWNLOAD              1034
#define IDC_ALT                         1034
#define IDC_FINISH                      1035
#define IDC_WIN                         1035
#define IDC_PREVIOUS                    1036
#define IDC_NEXT                        1037
#define IDC_SOUNDFILE                   1039
#define IDC_BROWSE                      1040
#define IDC_UPDATEEMAIL                 1045
#define IDC_EMAIL                       1046
#define IDC_CHANGEFONT                  1046
#define IDC_DOCKLEFT                    1048
#define IDC_DOCKTOP                     1049
#define IDC_DOCKRIGHT                   1050
#define IDC_DOCKBOTTOM                  1051
#define IDC_LEFT                        1052
#define IDC_WIDTH                       1053
#define IDC_CHANGENOTECOLOR             1053
#define IDC_TOP                         1055
#define IDC_DELETENOTES                 1055
#define IDC_TRANSPARANCYNORMAL          1056
#define IDC_CHARACTER                   1057
#define IDC_SETHOTKEY                   1058
#define IDC_SHIFT                       1059
#define IDC_CTRL                        1060
#define IDC_USEHOTKEY                   1061
#define IDC_STATUSTEXT                  1062
#define IDC_ADDRESS                     1064
#define IDC_USEDEFAULTSERVER            1065
#define IDC_PORT                        1066
#define IDC_PATH                        1067
#define IDC_TITLES                      1068
#define IDC_CHECK1                      1069
#define IDC_DELETE                      1070
#define IDC_RESTORE                     1071
#define IDC_NUMBEROFDELETEDNOTES        1072
#define IDC_SORTDESCENDING              1073
#define IDC_DOWNLOADAFTER               1075
#define IDC_INUSE                       1076
#define IDC_AVAILABLE                   1077
#define IDC_ADD                         1079
#define IDC_REMOVE                      1080
#define IDC_LANGUAGE                    1081
#define IDC_UP                          1081
#define IDC_DOWN                        1082
#define IDC_EDITLANGUAGE                1083
#define IDC_ADDLANGUAGE                 1084
#define IDC_STATIC3                     1085
#define IDC_STATIC4                     1086
#define IDC_STATIC5                     1087
#define IDC_STATIC6                     1088
#define IDC_ENGLISH                     1093
#define IDC_OTHERLANGUAGE               1094
#define IDC_INIFILE                     1099
#define IDC_ENGLISHNAME                 1100
#define IDC_RICHEDIT21                  1101
#define IDC_CHARSET                     1102
#define ID_ALARMTIMER                   2000
#define ID_NOTEMINIMIZE                 2001
#define ID_NOTECLOSE                    2002
#define ID_NOTEALARM                    2003
#define ID_NOTETITLE                    2004
#define ID_NOTETEXT                     2005
#define ID_SAVETIMER                    2006
#define ID_NOTEBLINK                    2007
#define ID_GETNOTESFROMTHREAD           2008
#define ID_GETVERSIONFROMTHREAD         2009
#define ID_NOTEBULLET                   2010
#define ID_STARTCONNECTTOINTERNET       2011
#define ID_SLIDERIGHT                   2012
#define ID_SLIDELEFT                    2013
#define ID_UNDERLINE                    2014
#define ID_ITALIC                       2015
#define ID_BOLD                         2016
#define ID_STRIKEOUT                    2017
#define ID_PRESSEDLEFTBUTTONONTRAYICON  2018
#define ID_TRAYSINGLECLICK              2019
#define ID_MINIMIZEDMENUITEM            10000
#define ID_MINIMIZEDMENUITEM1           10001
#define ID_MINIMIZEDMENUITEM2           10002
#define ID_MINIMIZEDMENUITEM3           10003
#define ID_MINIMIZEDMENUITEM4           10004
#define ID_MINIMIZEDMENUITEM5           10005
#define ID_MINIMIZEDMENUITEM6           10006
#define ID_MINIMIZEDMENUITEM7           10007
#define ID_MINIMIZEDMENUITEM8           10008
#define ID_MINIMIZEDMENUITEM9           10009
#define ID_MINIMIZEDMENUITEM10          10010
#define ID_MINIMIZEDMENUITEM11          10011
#define ID_MINIMIZEDMENUITEM12          10012
#define ID_MINIMIZEDMENUITEM13          10013
#define ID_MINIMIZEDMENUITEM14          10014
#define ID_MINIMIZEDMENUITEM15          10015
#define ID_MINIMIZEDMENUITEM16          10016
#define ID_MINIMIZEDMENUITEM17          10017
#define ID_MINIMIZEDMENUITEM18          10018
#define ID_MINIMIZEDMENUITEM19          10019
#define ID_TRAYMAIN_NEWNOTE             32771
#define ID_TRAYMAIN_STAYONTOP           32772
#define ID_TRAYMAIN_MINIMIZEALL         32773
#define ID_TRAYMAIN_RESTOREALL          32774
#define ID_TRAYMAIN_REGISTER            32775
#define ID_TRAYMAIN_OPTIONS             32776
#define ID_TRAYMAIN_ABOUT               32777
#define ID_POPUPMENU_COPY               32778
#define ID_POPUPMENU_CUT                32779
#define ID_POPUPMENU                    32780
#define ID_POPUPMENU_PASTE              32781
#define ID_POPUPMENU_FONT               32782
#define ID_POPUPMENU_NOTECOLOR          32783
#define ID_POPUPMENU_SETTITLE           32784
#define ID_POPUPMENU_ALARM              32785
#define ID_TRAYMAIN_HELP                32810
#define ID_POPUPMENU_EMAIL              32811
#define ID_TRAYMAIN_IMPORTEXPORT_IMPORT 32813
#define ID_TRAYMAIN_IMPORTEXPORT_EXPORT 32814
#define ID_POPUPMENU_SENDTO_PLAINTEXT   32817
#define ID_POPUPMENU_SENDTO_HTML        32818
#define ID_TRAYMAIN_ENTERKEY            32821
#define ID_BUTTON32824                  32824
#define ID_TRAYMAIN_UPLOADDOWNLOAD_UPLOADNOTES 32826
#define ID_TRAYMAIN_UPLOADDOWNLOAD_DOWNLOADNOTES 32827
#define ID_POPUPMENU_PRINT              32831
#define ID_BUTTON32832                  32832
#define ID_POPUPMENU_SENDTO             32833
#define ID_TRAYMAIN_RESTOREALL_FDF      32840
#define ID_TRAYMAIN_VISITANOTEWEBSITE   32852
#define ID_TRAYMAIN_SENDBUGG            32855
#define ID_TRAYMAIN_RESTORE_RESTOREALL  32857
#define ID_TRAYMAIN_FAQ                 32859
#define ID_TRAYMAIN_RECYCLEBIN          32863
#define ID_TRAYMAIN_CHECKFORUPDATES     32864
#define ID_POPUPMENU_UNDO               32865

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
